
import "./globals.css";
import Header from "@/components/Header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import ThemeContextProvider from "@/context/theme-context";
import Footer from "@/components/Footer";

// Use system fonts to avoid network fetch failures during build

export const metadata = {
	title: "Jacob's Portfolio",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.png", // Add your favicon path here
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="!scroll-smooth">
			<head>
				<link rel="icon" href="/favicon.png" type="image/png" sizes="any" />
			</head>

                        <body
                                className="relative text-gray-50 font-sans"
                        >
                                {/* Background gradient */}
                                <div className="fixed inset-0 -z-20 bg-gradient-to-br from-slate-900 via-gray-900 to-black"></div>

                                <ThemeContextProvider>
                                        <ActiveSectionContextProvider>
                                                <Header />
                                                {children}
                                                <Footer />
                                        </ActiveSectionContextProvider>
                                </ThemeContextProvider>
                        </body>
		</html>
	);
}
