
import "./globals.css";
import Header from "@/components/Header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import ThemeContextProvider from "@/context/theme-context";
import Footer from "@/components/Footer";
import Starfield from "@/components/Starfield";

// Use system fonts to avoid network fetch failures during build

export const metadata = {
	title: "Jacob's Portfolio",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.png", // Add your favicon path here
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
                <html lang="en" className="!scroll-smooth">
                        <head>
                                <meta name="viewport" content="width=device-width, initial-scale=1" />
                                <link rel="icon" href="/favicon.png" type="image/png" sizes="any" />
                        </head>

                        <body
                                className="relative text-gray-50 font-sans"
                        >
                                {/* Animated starfield background */}
                                <Starfield />
                                {/* Dark overlay for readability */}
                                <div className="fixed inset-0 -z-30 bg-gradient-to-b from-black/60 via-black/80 to-black" />

                                <ThemeContextProvider>
                                        <ActiveSectionContextProvider>
                                                <Header />
                                                {children}
                                                <Footer />
                                        </ActiveSectionContextProvider>
                                </ThemeContextProvider>
                        </body>
		</html>
	);
}
